package com.meridian.platform.shared.domain.audit;

public enum BusinessAuditAction {
    CUSTOMER_PROFILE_CREATED,
    CUSTOMER_PROFILE_UPDATED,
    CUSTOMER_PROFILE_COMPLETED,
    CUSTOMER_BANK_ACCOUNT_ADDED,
    CUSTOMER_BANK_ACCOUNT_MADE_PRIMARY,
    CUSTOMER_BANK_ACCOUNT_DEACTIVATED,
    SALARY_ADVANCE_APPLICATION_SUBMITTED,
    SALARY_ADVANCE_LIMIT_INITIALIZED,
    SALARY_ADVANCE_LIMIT_REFRESHED,
    SALARY_ADVANCE_LIMIT_RESERVED,
    LOAN_REVIEW_STARTED,
    REVIEW_RECOMMENDATION_RECORDED,
    APPROVAL_DECISION_RECORDED,
    APPROVED_OFFER_GENERATED,
    APPROVED_OFFER_ACCEPTED,
    APPROVED_OFFER_DECLINED,
    OFFER_EXPIRED,
    RESERVATION_RELEASED
}
