package com.meridian.platform.shared.domain.audit;

public enum BusinessAuditEntityType {
    CUSTOMER,
    CUSTOMER_BANK_ACCOUNT,
    LOAN_APPLICATION,
    SALARY_ADVANCE_LIMIT_MOVEMENT,
    REVIEW_RECOMMENDATION,
    APPROVAL_DECISION,
    APPROVED_OFFER,
    DOCUMENT_CHECKLIST,
    DOCUMENT_CHECKLIST_ITEM,
    DOCUMENT_VERSION,
    DOCUMENT_REVIEW_DECISION,
    LOAN_REVIEW_CYCLE,
    LOAN_CORRECTION_REQUEST,
    LOAN_CORRECTION_TASK,
    SALARY_ADVANCE_VERIFICATION
}
