package com.meridian.platform.loan.domain.model;

public enum ContractReadinessBlockerCode {
    INVALID_APPLICATION_STATE,
    ACCEPTED_OFFER_MISSING,
    ACCEPTED_OFFER_NOT_ACCEPTED,
    CURRENT_CONTRACT_MISSING,
    CONTRACT_VERSION_STALE,
    ACKNOWLEDGMENT_MISSING,
    CUSTOMER_INACTIVE,
    CAPTURED_ACCOUNT_MISSING,
    CAPTURED_ACCOUNT_INACTIVE,
    DOCUMENTS_NOT_PROCESSING_READY,
    ACTIVE_CORRECTION_REQUEST,
    UCL_VERIFICATION_INVALID,
    SALARY_ADVANCE_RESERVATION_INVALID,
    SALARY_ADVANCE_RESERVATION_RELEASED,
    PRODUCT_CONTRACT_EXECUTION_UNSUPPORTED,
    READINESS_ALREADY_CONFIRMED,
    CONFLICTING_COMPLETED_TRANSITION
}
