package com.meridian.platform.loan.domain.model;

public enum LoanApplicationTransitionAction {
    SUBMIT_APPLICATION,
    COMPLETE_DOCUMENT_UPLOADS,
    START_REVIEW,
    RECOMMEND_APPROVAL,
    RECOMMEND_REJECTION,
    RETURN_TO_CUSTOMER_REVISION,
    REQUEST_STAFF_CORRECTION,
    APPROVE,
    REJECT,
    RETURN_TO_LOAN_OFFICER_REVIEW,
    REQUEST_CUSTOMER_OR_STAFF_CORRECTION,
    RESUBMIT_CORRECTION,
    GENERATE_APPROVED_OFFER,
    ACCEPT_APPROVED_OFFER,
    DECLINE_APPROVED_OFFER,
    EXPIRE_APPROVED_OFFER,
    CONFIRM_DISBURSEMENT_READINESS,
    CONFIRM_MANUAL_DISBURSEMENT
}
