package com.meridian.platform.loan.domain.model;

public enum LoanApplicationTransitionAction {
    APPLICATION_SUBMITTED,
    REVIEW_STARTED,
    RECOMMEND_APPROVAL,
    RECOMMEND_REJECTION,
    RETURN_TO_CUSTOMER_REVISION,
    REQUEST_STAFF_CORRECTION,
    APPROVE,
    REJECT,
    RETURN_TO_LOAN_OFFICER_REVIEW,
    REQUEST_CUSTOMER_OR_STAFF_CORRECTION,
    APPROVED_OFFER_GENERATED,
    OFFER_ACCEPTED,
    OFFER_DECLINED,
    OFFER_EXPIRED
}
