package com.meridian.platform.shared.application.audit;

public enum AuditAction {
    APPLICATION_SUBMITTED,
    SALARY_ADVANCE_LIMIT_INITIALIZED,
    SALARY_ADVANCE_LIMIT_REFRESHED,
    SALARY_ADVANCE_LIMIT_RESERVED,
    REVIEW_STARTED,
    REVIEW_RECOMMENDATION_RECORDED,
    APPROVAL_DECISION_RECORDED,
    APPROVED_OFFER_GENERATED,
    OFFER_ACCEPTED,
    OFFER_DECLINED,
    OFFER_EXPIRED,
    SALARY_ADVANCE_RESERVATION_RELEASED
}