import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { formatDateOnly, formatTimestamp, formatVnd } from '@/lib/format/presentation'
import type { LoanAccount } from '../api/contracts'
import { ServicingStatusBadge } from './ServicingStatusBadge'

function Fact({ label, children }: { label: string; children: React.ReactNode }) {
  return <div className="min-w-0"><dt className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</dt><dd className="mt-1 break-words font-semibold">{children}</dd></div>
}

export function LoanAccountEvidence({ account }: { account: LoanAccount }) {
  const servicing = account.servicing
  return <>
    <Card><CardHeader><CardTitle>LoanAccount terms</CardTitle></CardHeader><CardContent><dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Fact label="Account number">{account.accountNumber}</Fact><Fact label="Status"><ServicingStatusBadge status={account.status} /></Fact><Fact label="Activated">{formatTimestamp(account.activatedAt)}</Fact><Fact label="Originated principal">{formatVnd(account.originatedPrincipal)}</Fact><Fact label="Approved term">{account.approvedTermMonths} months</Fact><Fact label="Total interest">{formatVnd(account.totalInterest)}</Fact><Fact label="Total fee">{formatVnd(account.totalFee)}</Fact><Fact label="Total repayment">{formatVnd(account.totalRepayment)}</Fact></dl></CardContent></Card>
    <Card><CardHeader><CardTitle>Current servicing summary</CardTitle></CardHeader><CardContent><dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Fact label="Principal paid">{formatVnd(servicing.principalPaid)}</Fact><Fact label="Interest paid">{formatVnd(servicing.interestPaid)}</Fact><Fact label="Fee paid">{formatVnd(servicing.feePaid)}</Fact><Fact label="Total paid">{formatVnd(servicing.totalPaid)}</Fact><Fact label="Principal outstanding">{formatVnd(servicing.principalOutstanding)}</Fact><Fact label="Interest outstanding">{formatVnd(servicing.interestOutstanding)}</Fact><Fact label="Fee outstanding">{formatVnd(servicing.feeOutstanding)}</Fact><Fact label="Total outstanding">{formatVnd(servicing.totalOutstanding)}</Fact><Fact label="Evaluation date">{formatDateOnly(servicing.servicingEvaluationDate)}</Fact><Fact label="Last payment date">{formatDateOnly(servicing.lastPaymentValueDate)}</Fact><Fact label="Last recorded">{formatTimestamp(servicing.lastPaymentRecordedAt)}</Fact></dl></CardContent></Card>
    <Card><CardHeader><CardTitle>Permanently masked destination</CardTitle><p className="text-sm text-muted-foreground">CP8 never reveals or decrypts the contract-bound destination.</p></CardHeader><CardContent><dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Fact label="Bank">{account.disbursementDestination.bankName} ({account.disbursementDestination.bankCode})</Fact><Fact label="Account holder">{account.disbursementDestination.accountHolderName}</Fact><Fact label="Account number"><span className="font-mono">{account.disbursementDestination.maskedAccountNumber}</span></Fact></dl></CardContent></Card>
    <Card><CardHeader><CardTitle>Immutable final schedule</CardTitle><p className="text-sm text-muted-foreground">Schedule {account.finalRepaymentSchedule.scheduleId} · FINAL · version {account.finalRepaymentSchedule.version} · {formatDateOnly(account.finalRepaymentSchedule.firstDueDate)} to {formatDateOnly(account.finalRepaymentSchedule.lastDueDate)}</p></CardHeader><CardContent><div className="overflow-x-auto rounded-md border"><table className="w-full min-w-[82rem] text-left text-sm"><thead className="bg-muted text-xs uppercase text-muted-foreground"><tr><th className="p-3">Installment</th><th className="p-3">Due</th><th className="p-3">Status</th><th className="p-3">Principal due</th><th className="p-3">Interest due</th><th className="p-3">Fee due</th><th className="p-3">Total due</th><th className="p-3">Paid</th><th className="p-3">Outstanding</th><th className="p-3">Evaluated</th><th className="p-3">Last payment</th></tr></thead><tbody>{account.finalRepaymentSchedule.items.map((item) => <tr key={item.installmentNumber} className="border-t"><td className="p-3 font-semibold">{item.installmentNumber}</td><td className="p-3">{formatDateOnly(item.dueDate)}</td><td className="p-3"><ServicingStatusBadge status={item.servicing.status} /></td><td className="p-3">{formatVnd(item.principalDue)}</td><td className="p-3">{formatVnd(item.interestDue)}</td><td className="p-3">{formatVnd(item.feeDue)}</td><td className="p-3 font-semibold">{formatVnd(item.totalDue)}</td><td className="p-3">{formatVnd(item.servicing.totalPaid)}</td><td className="p-3">{formatVnd(item.servicing.totalOutstanding)}</td><td className="p-3">{formatDateOnly(item.servicing.statusEvaluationDate)}</td><td className="p-3">{formatDateOnly(item.servicing.lastPaymentValueDate)}</td></tr>)}</tbody></table></div></CardContent></Card>
  </>
}
