import { matchPath } from 'react-router-dom'
import {
  STAFF_APPROVAL_QUEUE_ROUTE, STAFF_DECISION_CASE_ROUTE,
  STAFF_CONTRACT_QUEUE_ROUTE, STAFF_CONTRACT_CASE_ROUTE,
  STAFF_CORRECTION_QUEUE_ROUTE, STAFF_CORRECTION_CASE_ROUTE,
  STAFF_DISBURSEMENT_QUEUE_ROUTE, STAFF_DISBURSEMENT_CASE_ROUTE,
  STAFF_DOCUMENT_QUEUE_ROUTE, STAFF_DOCUMENT_CASE_ROUTE,
  STAFF_SERVICING_QUEUE_ROUTE, STAFF_LOAN_ACCOUNT_ROUTE, STAFF_REPAYMENT_ENTRY_ROUTE,
  STAFF_SETTLEMENT_QUEUE_ROUTE, STAFF_SETTLEMENT_CASE_ROUTE,
  STAFF_CLOSURE_QUEUE_ROUTE, STAFF_CLOSURE_CASE_ROUTE,
} from './staff-route-metadata'

const workspaceParents = [
  [STAFF_DECISION_CASE_ROUTE, STAFF_APPROVAL_QUEUE_ROUTE],
  [STAFF_CONTRACT_CASE_ROUTE, STAFF_CONTRACT_QUEUE_ROUTE],
  [STAFF_CORRECTION_CASE_ROUTE, STAFF_CORRECTION_QUEUE_ROUTE],
  [STAFF_DISBURSEMENT_CASE_ROUTE, STAFF_DISBURSEMENT_QUEUE_ROUTE],
  [STAFF_DOCUMENT_CASE_ROUTE, STAFF_DOCUMENT_QUEUE_ROUTE],
  [STAFF_LOAN_ACCOUNT_ROUTE, STAFF_SERVICING_QUEUE_ROUTE],
  [STAFF_REPAYMENT_ENTRY_ROUTE, STAFF_SERVICING_QUEUE_ROUTE],
  [STAFF_SETTLEMENT_CASE_ROUTE, STAFF_SETTLEMENT_QUEUE_ROUTE],
  [STAFF_CLOSURE_CASE_ROUTE, STAFF_CLOSURE_QUEUE_ROUTE],
] as const

export function navigationContextPath(pathname: string): string {
  return workspaceParents.find(([workspace]) => matchPath({ path: workspace.path, end: true }, pathname))?.[1].path ?? pathname
}
